# Numpy Practice
## 과제 안내 
- 답안을 작성하여 ipynb 파일로 구글 드라이브 \[Assignment\] - \[개인 폴더\]로 업로드하시면 됩니다.  
- 출력 예시는 본 파일 하단에 수록되어 있습니다.

# Practice

In [ ]:
import numpy as np

## P.1-1

Numpy로 100개의 원소를 가지는 1차원 행렬을 생성해봅시다.  
단 원소는 **1부터** 차례대로 **홀수**만 가집니다.   
그리고 각 원소의 자료형은 float64으로 변환해주세요.  
생성한 Numpy 배열의 이름은  np_arr1으로 해주세요.


In [ ]:
########## P.1-1 Write your answer here

########################################
print(np_arr1)

## P.1-2
앞서 제작한 1차원 행렬 np_arr1을 10 X 10 행렬로 변환해 봅시다.
변환한 행렬의 이름은 np_arr2로 해주세요.

In [ ]:
########## P.1-2 Write your answer here

########################################
print(np_arr2)

## P.1-3
np_arr2에서 만약 원소의 값이 50 이상이라면 그 값에 2를 곱해봅시다.  
그 결과는 np_arr3 변수에 저장해주세요.  
(for/while 문법을 사용하지 않고 numpy 메서드를 사용하여 구현해봅시다.)

In [ ]:
########## P.1-3 Write your answer here

########################################
print(np_arr3)

## P.1-4
np_arr3에서 3의 배수의 개수를 세어 봅시다.  
그 결과는 cnt_div 변수에 저장해주세요.  
(for/while 문법을 사용하지 않고 numpy 메서드를 사용하여 구현해봅시다.)

In [ ]:
########## P.1-4 Write your answer here

########################################
print(cnt_div)

## p.1-5
np_arr3에서 행 각각의 평균을 구해봅시다.  
그 결과는 np_avg에 저장해주세요.

In [ ]:
########## P.1-5 Write your answer here

########################################
print(np_avg)

## P.1-6
np_arr3의 각 원소에 그 행의 평균을 빼 봅시다. (앞서 구한 np_avg를 사용하여 구해봅시다.)  
그리고 각각의 원소에 절댓값을 취해 봅니다.  
그 결과를 np_arr4에 저장합시다.

In [ ]:
########## P.1-6 Write your answer here

########################################
print(np_arr4)

## P.1-7
np_arr4 전체 원소의 표준편차를 구해봅시다.
그 결과는 result에 저장해주세요.

In [ ]:
########## P.1-7 Write your answer here

########################################
print(result)

# Self Check

## P.1-1
```
[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.  21.  23.  25.  27.
  29.  31.  33.  35.  37.  39.  41.  43.  45.  47.  49.  51.  53.  55.
  57.  59.  61.  63.  65.  67.  69.  71.  73.  75.  77.  79.  81.  83.
  85.  87.  89.  91.  93.  95.  97.  99. 101. 103. 105. 107. 109. 111.
 113. 115. 117. 119. 121. 123. 125. 127. 129. 131. 133. 135. 137. 139.
 141. 143. 145. 147. 149. 151. 153. 155. 157. 159. 161. 163. 165. 167.
 169. 171. 173. 175. 177. 179. 181. 183. 185. 187. 189. 191. 193. 195.
 197. 199.]
```

## P.1-2
```
[[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.]
 [ 21.  23.  25.  27.  29.  31.  33.  35.  37.  39.]
 [ 41.  43.  45.  47.  49.  51.  53.  55.  57.  59.]
 [ 61.  63.  65.  67.  69.  71.  73.  75.  77.  79.]
 [ 81.  83.  85.  87.  89.  91.  93.  95.  97.  99.]
 [101. 103. 105. 107. 109. 111. 113. 115. 117. 119.]
 [121. 123. 125. 127. 129. 131. 133. 135. 137. 139.]
 [141. 143. 145. 147. 149. 151. 153. 155. 157. 159.]
 [161. 163. 165. 167. 169. 171. 173. 175. 177. 179.]
 [181. 183. 185. 187. 189. 191. 193. 195. 197. 199.]]
```

## P.1-3
```
[[  1.   3.   5.   7.   9.  11.  13.  15.  17.  19.]
 [ 21.  23.  25.  27.  29.  31.  33.  35.  37.  39.]
 [ 41.  43.  45.  47.  49. 102. 106. 110. 114. 118.]
 [122. 126. 130. 134. 138. 142. 146. 150. 154. 158.]
 [162. 166. 170. 174. 178. 182. 186. 190. 194. 198.]
 [202. 206. 210. 214. 218. 222. 226. 230. 234. 238.]
 [242. 246. 250. 254. 258. 262. 266. 270. 274. 278.]
 [282. 286. 290. 294. 298. 302. 306. 310. 314. 318.]
 [322. 326. 330. 334. 338. 342. 346. 350. 354. 358.]
 [362. 366. 370. 374. 378. 382. 386. 390. 394. 398.]]
 ```

## P.1-4
```
33
```

# p.1-5
```
[ 10.   30.   77.5 140.  180.  220.  260.  300.  340.  380. ]
```

## P.1-6
```
[[ 9.   7.   5.   3.   1.   1.   3.   5.   7.   9. ]
 [ 9.   7.   5.   3.   1.   1.   3.   5.   7.   9. ]
 [36.5 34.5 32.5 30.5 28.5 24.5 28.5 32.5 36.5 40.5]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]
 [18.  14.  10.   6.   2.   2.   6.  10.  14.  18. ]]
```


## P.1-7
```
8.94776508408664
```